name: Run Test

on:
  push:
    branches: [ master ]
  pull_request:

env:
  MAVEN_OPTS: --add-opens=java.rmi/sun.rmi.transport=org.apache.tomcat.embed.core

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test with maven
        run: mvn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          directory: ./coverage/reports/
          env_vars: OS
          fail_ci_if_error: true
          files: /home/runner/work/MyBackendFramework/MyBackendFramework/aggregate-report/target/site/jacoco-aggregate/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true