name: Run Test

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test with maven
        run: mvn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          directory: ./coverage/reports/
          env_vars: OS
          fail_ci_if_error: true
          files: /home/runner/work/QuakFramework/QuakFramework/aggregate-jacoco-reports/target/site/jacoco-aggregate/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
#      - name: Maven Deploy
#        run: mvn -s settings.xml clean deploy -Dmaven.resolver.transport=wagon -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
#        env:
#          SNAPSHOT_REPOSITORY_HOST: ${{ secrets.MAVEN_SNAPSHOT_HOST }}